export default {
  width: "500px",
  height: "700px",
  Provice: {
    "Bogota D.C.": "Bogota",
    Antioquia: "Antioquia",
    "Departamento del Valle del Cauca": "Valle del Cauca",
    Atlántico: "Atlántico",
    "Departamento de Santander": "",
    Cundinamarca: "",
    "Departamento de Narino": "Narino",
    "Departamento de Risaralda": "Risaralda",
    "Departamento del Meta": "Meta",
    "Departamento de Caldas": "Caldas",
    "Departamento de Tolima": "Tolima",
    "Departamento del Huila": "Huila",
    "Departamento de Norte de Santander": "Norte de Santander",
    "Departamento de Cordoba": "Cordoba",
    "Departamento de Boyaca": "Boyaca",
    "Departamento del Cauca": "Cauca",
    "Departamento del Magdalena": "Magdalena",
    "Departamento de Bolivar": "Bolivar",
    "Departamento de Casanare": "Casanare",
    "Quindio Department": "Quindio Department",
    "Departamento del Cesar": "Cesar",
    "Departamento del Putumayo": "Putumayo",
    "Departamento de Sucre": "Sucre",
    "Departamento del Caqueta": "Caqueta",
    "Departamento del Choco": "Choco",
    "Departamento de Arauca": "Arauca",
    "Departamento de La Guajira": "La Guajira",
    "Departamento del Vichada": "Vichada",
    Amazonas: "Amazonas",
    "Departamento del Guaviare": "Guaviare",
    "Departamento del Guainia": "Guainia",
  },
};
